version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-user_database}

  passauth:
    image: passauth
    restart: always
    ports:
      - 3000:3000
    build: ./
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-lib_database}
      - DB_HOST=mongodb://mongodb:27017
    volumes:
      - ./routes:/./routes
      - ./config:/./config
      - ./views:/./views
    depends_on:
      - mongodb
    command: npm run dev
